# Account Service Configuration
spring:
  application:
    name: account-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}
  
  # Jackson configuration
  jackson:
    default-property-inclusion: non-null
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: false
    time-zone: UTC
    date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
  
  # Database configuration
  datasource:
    url: jdbc:h2:mem:accountdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  
  h2:
    console:
      enabled: true
      path: /h2-console
  
  # JPA configuration
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format-sql: true
        use-sql-comments: true
        batch-size: 25
        order-inserts: true
        order-updates: true
        jdbc:
          time-zone: UTC
  
  # Flyway configuration
  flyway:
    enabled: false
  
  # Web configuration
  web:
    resources:
      add-mappings: false

# Server configuration
server:
  port: ${PORT:8092}
  servlet:
    context-path: /
  error:
    include-message: on-param
    include-binding-errors: on-param
    include-stacktrace: on-param

# Management configuration  
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: when-authorized
      show-components: when-authorized
  prometheus:
    metrics:
      export:
        enabled: true

# Logging configuration
logging:
  level:
    root: INFO
    '[com.openbank]': DEBUG
    '[org.springframework.security]': INFO
    '[org.hibernate.SQL]': DEBUG
    '[org.hibernate.type.descriptor.sql.BasicBinder]': TRACE
